### ISSUE TITLE
Implement simple database loader

### ISSUE THREAD

**Issue by Satrige** [Satrige/rustqlight#28]
Since we wanna our results persist on disk, we need to implement a loader for it.

Let's keep it simple for the beginning.
The database on disk should have the next structure:
```
${database_folder}/
${database_folder}/db_struct.yaml
${database_folder}/${table1}
${database_folder}/${table2}
```

Where `${database_folder}/db_struct.yaml` has the next struct:
```yaml
db_name: db_name
tables:
  - table_name: users
    table_structure:
      - row_name: id
        row_type: integer
      - row_name: name
        row_type: string
      - row_name: email
        row_type: string
```

And the `${database_folder}/${table1}` is the binary representation of the table contents
